name: Pylint

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pylint and its dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Analyzing application code with pylint
      run: |
        pylint $(find mlynek -name "*.py")
