name: UnitTests

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pytest and its dependencies
      run: |
        python -m pip install pytest pytest-cov coverage
    - name: Run unit tests
      run: |
        #!/bin/bash
        export PYTHONPATH=mlynek
        python -m pytest mlynektests/ --cov
    - name: Run coverage
      run: |
        #!/bin/bash
        python -m coverage html
    - name: Archive report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: |
          htmlcov
